Feature/rdm 13106 search party collection field name validation
hmcts/ccd-definition-store-api pull request #1148
Opened 2022-02-09 10:51 UTC by sem-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDM-13106

### Change description ###
Validation of SearchPartyTab property fields when CollectionFieldName is in use

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-02-15 09:27 UTC, mattnayler requested changes

2022-02-16 02:20 UTC, mattnayler commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/DotNotationValidator.java
> +        expression -> SPIT_FUNCTION.apply(expression, DOT_SEPARATOR);
Resolved in e4801dcc4b856a6eabbd6655e61eb00fff987fa2

2022-02-16 02:20 UTC, mattnayler commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/DotNotationValidator.java
> +            final String[] splitDotNotationExpression = DOT_SEPARATOR_SPLIT_FUNCTION.apply(expression);
Resolved in e4801dcc4b856a6eabbd6655e61eb00fff987fa2

2022-02-16 02:20 UTC, mattnayler commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/DotNotationValidator.java
> +                .subList(1, splitDotNotationExpression.length);
Resolved in e4801dcc4b856a6eabbd6655e61eb00fff987fa2

2022-02-16 02:21 UTC, mattnayler commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/DotNotationValidator.java
> +            final Set<ComplexFieldEntity> complexFieldsBelongingToParent = fieldType.getComplexFields();
Resolved in e4801dcc4b856a6eabbd6655e61eb00fff987fa2

2022-02-16 02:21 UTC, mattnayler commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/DotNotationValidator.java
> +            performCheck(splitDotNotationExpression, parentComplexFields, sheetName, columnName);
Resolved in e4801dcc4b856a6eabbd6655e61eb00fff987fa2

2022-02-16 02:22 UTC, mattnayler commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SearchPartyValidator.java
> +                // Is this validation #validateSearchPartyCollectionFieldName() still needed?
Resolved in e4801dcc4b856a6eabbd6655e61eb00fff987fa2

2022-02-16 02:22 UTC, mattnayler commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SearchPartyValidator.java
> +        }
Resolved in e4801dcc4b856a6eabbd6655e61eb00fff987fa2, refactored with `DotNotationValidator`

2022-02-16 02:23 UTC, mattnayler commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SearchPartyValidator.java
> +    private static final String COLLECTION_FIELD_TYPE = "Collection";
Resolved in e4801dcc4b856a6eabbd6655e61eb00fff987fa2, used `FieldTypeUtils.BASE_COLLECTION`

2022-02-16 02:23 UTC, mattnayler commented on excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SearchPartyValidatorTest.java
> +    private static final String COLLECTION_DATA_TYPE = "Collection";
Resolved in e4801dcc4b856a6eabbd6655e61eb00fff987fa2, used `FieldTypeUtils.BASE_COLLECTION`

2022-02-16 02:24 UTC, mattnayler commented on aat/src/aat/resources/features/F-099 SearchParty (GlobalSearch)/F-099.feature
> +    And the response has all other details as expected
Resolved in e4801dcc4b856a6eabbd6655e61eb00fff987fa2

2022-02-16 09:30 UTC, mattnayler approved these changes
👍 LGTM

2022-02-16 10:25 UTC, KleoG commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/DotNotationValidator.java
> +    public static final BiFunction<String, String, String[]> SPIT_FUNCTION =
👍

2022-02-16 10:27 UTC, KleoG commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/DotNotationValidator.java
> +        expression -> SPIT_FUNCTION.apply(expression, DOT_SEPARATOR);
👍

2022-02-16 10:28 UTC, KleoG commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/DotNotationValidator.java
> +            final String[] splitDotNotationExpression = DOT_SEPARATOR_SPLIT_FUNCTION.apply(expression);
👍

2022-02-16 10:38 UTC, KleoG commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/DotNotationValidator.java
> +                .subList(1, splitDotNotationExpression.length);
👍

2022-02-16 10:48 UTC, KleoG commented on aat/src/aat/resources/features/F-099 SearchParty (GlobalSearch)/F-099.feature
> +    And the response has all other details as expected
👍

2022-02-16 11:05 UTC, KleoG commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/DotNotationValidator.java
> +            performCheck(splitDotNotationExpression, parentComplexFields, sheetName, columnName);
👍

2022-02-16 11:14 UTC, KleoG commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SearchPartyValidator.java
> +                // Is this validation #validateSearchPartyCollectionFieldName() still needed?
👍

2022-02-16 11:16 UTC, KleoG commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SearchPartyValidator.java
> +        }
👍

2022-02-16 11:16 UTC, KleoG commented on aat/src/aat/resources/features/F-099 SearchParty (GlobalSearch)/F-099.feature
> +    And the response has all other details as expected
👍

2022-02-16 11:17 UTC, KleoG commented on excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SearchPartyValidatorTest.java
> +    private static final String COLLECTION_DATA_TYPE = "Collection";
👍

2022-02-16 11:19 UTC, KleoG commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SearchPartyValidator.java
> +    private static final String COLLECTION_FIELD_TYPE = "Collection";
👍

2022-02-16 11:24 UTC, KleoG commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/DotNotationValidator.java
> +            final Set<ComplexFieldEntity> complexFieldsBelongingToParent = fieldType.getComplexFields();
👍

2022-02-16 11:27 UTC, KleoG commented on excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SearchPartyValidator.java
> +            result = complexFieldEntity.getFieldType();
👍

2022-02-16 11:27 UTC, KleoG approved these changes
LGTM 👍

2022-02-17 14:56 UTC, merged