CCD-4412: Changes to jenkins files
hmcts/ccd-definition-store-api pull request #1368
Opened 2023-04-04 20:04 UTC by kerry-anne-mclaughlin

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CCD-4412

### Change description ###

Replacing deprecated internal urls with up to date versions in jenkins and test files

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-04-05 09:16 UTC, rajaram-nagarajan requested changes

2023-04-05 09:16 UTC, rajaram-nagarajan commented on Jenkinsfile_nightly
>  env.BEFTA_RESPONSE_HEADER_CHECK_POLICY="JUST_WARN"
CCD_STUB_SERVICE_URI_BASE and S2S_URL can be fixed as well

2023-04-05 09:16 UTC, rajaram-nagarajan commented on Jenkinsfile_CNP
CCD_STUB_SERVICE_URI_BASE can be fixed

2024-02-28 21:37 UTC, lang-ben approved these changes

2024-03-01 10:46 UTC, closed without merging