ACA-68 - bump befta-fw version to use pre release
hmcts/ccd-definition-store-api pull request #814
Opened 2020-11-17 13:18 UTC by sullivangareth

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2020-11-17 15:07 UTC, mattnayler approved these changes

2020-11-17 15:12 UTC, mattnayler approved these changes
All green: and hmcts/befta-fw#118 OK.  So approved if updated to reflect final `befta-fw` release version.

2020-11-17 15:25 UTC, mattnayler requested changes
approved if updated to reflect final befta-fw release version.

2020-11-19 08:46 UTC, mattnayler approved these changes

2020-12-11 09:12 UTC, sullivangareth commented
Closing old, redundant PR

2020-12-11 09:12 UTC, closed without merging